site_name: SCI Document
site_url: https://gustaavv.github.io/SecureCloudInspector
repo_url: https://github.com/gustaavv/SecureCloudInspector
site_author: Gustaavv
copyright: Copyright &copy; 2024 Gustaavv

nav:
  - Home:
      - index.md
      - License: license.md
  - Getting Started:
      - Prerequisite: gettingStarted/prerequisite.md
      - Concepts: gettingStarted/concepts.md
  - User Guide:
      - Cli: userGuide/cli.md
      - Desktop: userGuide/desktop.md
      - Config Location: userGuide/configLocation.md
  - Architecture:
      - Encryption Mechanism: architecture/encryptionMechanism.md
      - Developer Guide: architecture/developerGuide.md
  - Others:
      - others/index.md

theme:
  name: material
  font:
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.tabs.link

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gustaavv/SecureCloudInspector

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js