site_name: SCI Document
site_url: https://gustaavv.github.io/SecureCloudInspector
repo_url: https://github.com/gustaavv/SecureCloudInspector
site_author: Gustaavv
copyright: Copyright &copy; 2024 Gustaavv

nav:
  - Home:
      - index.md
      - License: license.md
  - Getting Started:
      - gettingStarted/index.md
  - User Guide:
      - Desktop: userGuide/desktop.md
      - Cli: userGuide/cli.md
      - Config Location: userGuide/configLocation.md
  - Architecture:
      - Encryption Mechanism: architecture/encryptionMechanism.md
      - Developer Guide: architecture/developerGuide.md
  - Others:
      - others/others.md

theme:
  name: material
  font:
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gustaavv/SecureCloudInspector

markdown_extensions:
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format