name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Cli:
    runs-on: ubuntu-latest
    name: SCI-CLI build and release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get tag name
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            echo "Selected tag is: $TAG"
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "Error: This workflow requires a tag to be selected. Exiting..."
            exit 1
          fi

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      
      - name: Build and publish
        run: |
          dotnet build --configuration Release
          dotnet publish ./SCICli/SCICli.csproj --configuration Release --output ./publish

      - name: Make artifacts
        run: zip -j ./publish/SCICli-${{ env.TAG }}-win64.zip ./publish/SCICli.exe

      - name: Copy release note
        run: |
          cat ./releaseNotes/${{ env.TAG }}.md >> body.md
          echo "" >> body.md

      - name: Generate checksum
        run: |
          echo "## Checksum for SCICli-${{ env.TAG }}-win64.zip" >> body.md
          echo "| Checksum | Value |" >> body.md
          echo "| -------- | ----- |" >> body.md
          zipPath="./publish/SCICli-${{ env.TAG }}-win64.zip"
          echo "| sha256   | $(sha256sum ${zipPath} | awk '{print $1}') |" >> body.md
          echo "| sha1   | $(sha1sum ${zipPath} | awk '{print $1}') |" >> body.md
          echo "| md5   | $(md5sum ${zipPath} | awk '{print $1}') |" >> body.md
          echo "" >> body.md

      - name: Upload to GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./publish/SCICli-${{ env.TAG }}-win64.zip
          bodyFile: body.md