name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Cli:
    runs-on: windows-latest
    name: SCI build and release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -match '^refs/tags/(.+)$') {
            $TAG = $Matches[1]
            Write-Host "Selected tag is: $TAG"
            echo "TAG=$TAG" >> $env:GITHUB_ENV
          } else {
            Write-Error "Error: This workflow requires a tag to be selected. Exiting..."
            exit 1
          }

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build and publish
        shell: pwsh
        run: |
          dotnet build ./SCIDesktop/SCIDesktop.csproj --configuration Release
          dotnet publish ./SCIDesktop/SCIDesktop.csproj --configuration Release --output ./publish/SCIDesktop

      - name: Make artifacts
        shell: pwsh
        run: |
          cd publish
          Compress-Archive -Path ./SCIDesktop -DestinationPath ./SCIDesktop-${{ env.TAG }}-win64.zip
          cd ..

      - name: Copy release note
        shell: pwsh
        run: |
          Get-Content "./releaseNotes/${{ env.TAG }}.md" | Out-File -Append -Encoding utf8 body.md
          Add-Content -Path body.md -Value "`n"

      - name: Generate checksum
        shell: pwsh
        run: |
          Add-Content -Path body.md -Value "## Checksum for SCIDesktop-${{ env.TAG }}-win64.zip`n"
          Add-Content -Path body.md -Value "| Checksum | Value |`n"
          Add-Content -Path body.md -Value "| -------- | ----- |`n"

          $zipPath = "./publish/SCIDesktop-${{ env.TAG }}-win64.zip"

          $sha256 = Get-FileHash $zipPath -Algorithm SHA256 | Select-Object -ExpandProperty Hash
          $sha1 = Get-FileHash $zipPath -Algorithm SHA1 | Select-Object -ExpandProperty Hash
          $md5 = Get-FileHash $zipPath -Algorithm MD5 | Select-Object -ExpandProperty Hash

          Add-Content -Path body.md -Value "| sha256   | $sha256 |`n"
          Add-Content -Path body.md -Value "| sha1   | $sha1 |`n"
          Add-Content -Path body.md -Value "| md5   | $md5 |`n"
          Add-Content -Path body.md -Value "`n"

      - name: Upload to GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./publish/SCIDesktop-${{ env.TAG }}-win64.zip
          bodyFile: body.md
